### ISSUE TITLE
Cryptographically weaker RSA implementation

### ISSUE THREAD

**Issue by HenkPoley** [drlippman/IMathAS#10]
An e of 3 is used in: https://github.com/drlippman/IMathAS/blob/8342d27518a0917644d6249356bd8aee08e17bfe/assessment/libs/crypto.php#L211

Quote: "However, much smaller values of e (such as 3) have been shown to be less secure in some settings" from: https://en.wikipedia.org/wiki/RSA_(crypto system)#Key_generation

References: http://crypto.stanford.edu/~dabo/abstracts/RSAattack-survey.html

**Comment by drlippman** [comment]
That library was not intended to actually "do" secure cryptography.  It is part of a set of functions intended for learning RSA, and e=3 was chosen to keep the numbers reasonable to play with.

**Comment by HenkPoley** [comment]
I understand that. The trouble is that people will find this implementation and try to use it.

E.g. from another broken RSA: http://stackoverflow.com/questions/33593140/how-to-generate-signature-and-keys-in-codeigniter-rsa-library

**Comment by drlippman** [comment]
Fair enough.  I'll add a comment in the header and the code that notes that the library should not be used for any real cryptography application. 


    On Wednesday, November 25, 2015 5:43 AM, HenkPoley <notifications@github.com> wrote:
 

 I understand that. The trouble is that people will find this implementation and try to use it.E.g. from another broken RSA: http://stackoverflow.com/questions/33593140/how-to-generate-signature-and-keys-in-codeigniter-rsa-library—
