### ISSUE TITLE
Assessment retakes do not save but do submit

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#11]
When taking an assessment (projects) students can save the answer to the  questions and come back and finish at a later time. This works correct however once the student submits and attempts to retake it, it no longer saves correctly.

**Comment by drlippman** [comment]
I am unable to replicate this issue.  Please detail the specific assessment settings and steps to replicate.

**Comment by ericvanboven** [comment]
Below are screenshots of an assessment. When the Reattempts different
versions checkbox is checked, it is not working correctly. When it is
unchecked it works fine.

Start an assessment, fill in an answer and click save. Go back to
assessment and answer(s) show up correctly. Submit assessment. Go back to
assessment to retake and answers will be blank (if Reattempts different
version checkbox is checked as it should), fill in answer(s) and click
save. Go back to assessment and answers are blank.

On Tue, Nov 17, 2015 at 10:06 AM, David Lippman <notifications@github.com>
wrote:

> I am unable to replicate this issue. Please detail the specific assessment
> settings and steps to replicate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drlippman/IMathAS/issues/11#issuecomment-157435816>.
>



-- 


*Eric Van Boven:* System Admin II

18401 N. 32nd Street, Phoenix, AZ  85032
phone | 607-78(77794)
email | eric.van.boven@paradisevalley.edu
website | www.paradisevalley.edu

**Comment by ericvanboven** [comment]
I was able to replicate this on myopenmath too.   I have a course with one assessment. 
Course ID:9779
Enter Course name: ZZZ111

**Comment by drlippman** [comment]
Ahh, finally figured out what you meant.  Curious.  I'll see if I can track the issue.
