### ISSUE TITLE
email head

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#110]
I get the following displayed when sending emails for Password resets. All the other emails that get sent have it appear correctly (Username lookups, messages). My config is set to $sendfrom = "MathAS <<noreply@domain.com>>"
(Password resets)
![mathas_noreply](https://user-images.githubusercontent.com/10040354/35025397-85b56708-fb02-11e7-87fa-b0959a3b8628.png)

(Message replys/sends, username requests)
![noreply_correct](https://user-images.githubusercontent.com/10040354/35025464-f17f398c-fb02-11e7-9bf7-703bcad04d50.png)

**Comment by drlippman** [comment]
It would appear that, as a part of their security work, Lumen fed the $sendfrom address through a sanitization script, which is probably stripping out the < and >.  Since $sendfrom is specified in the config by the site owner, it strikes me as unnecessary to do this.  I'll revert it for now.
