### ISSUE TITLE
Using local install of MathJax/MathTeX?

### ISSUE THREAD

**Issue by justineuro** [drlippman/IMathAS#114]
Two concerns:

1. Would it be possible to allow the using of a local install of MathJax? 
1. ... using MathTeX  instead of MimeTeX? 

Thanks.

**Comment by drlippman** [comment]
1) Go for it.  I keep a local copy of MathJax in the repo (though it's probably a bit out of date). Just change your `header.php` and `assessment/header.php` to point to it instead of the CDN.  I think the necessary code is already in the files and commented out.

2) Likewise, go for it.  The only thing dictating the image-fallback provider is the `$mathimgurl` setting in your `config.php`.  Feel free to customize it to point to a MathTeX install instead of MimeTeX.

**Comment by justineuro** [comment]
1. Got MathJax to work by uncommenting the lines pointing to the local `mathjax` repo from both `header.php` and `assessment/header.php`.  Thank you!
2. Changing `mimetex` to `mathtex` causes some problems in the rendering of some questions in my install.  Attached are files pertaining to these problems.  Apparently, for these questions `mathtex` seems to have a problem in finding the local `latex` install.  Examples are Questions with IDs 3, 14, and 28 in the Examples Set that comes with the IMathAS source code (examples installed using `installexamples.php`).  The zipped folder attached: [mathtexProb.zip](https://github.com/drlippman/IMathAS/files/1729973/mathtexProb.zip), contains 1) export file containing these three (3) questions; 2) screenshots; and, 3) a copy o the error image from `mathtex`.

**Comment by justineuro** [comment]
Oops, accidentally closed that one.  Let me re-open it.

**Comment by drlippman** [comment]
1. Glad that worked

2. Those sound like errors with your mathtex install, not with IMathAS.  I don't know anything about mathtex, so can't help with that.

**Comment by justineuro** [comment]
Thank you, David, for all the help!  Let me look further into my `mathtex` install for Concern #2.

**Comment by justineuro** [comment]
**Concern 2 solved!**  I finally managed to get `mathtex` to process the `\matrix` request.  I eventually recompiled `mathtex` using the **-DNEWPACKAGE=\\"filename\\"** and the **-DNEWCOMMAND=\\"filename\\"** options to give my `mathex` install the capability to process a `\matrix` command request.

- the `-DNEWPACKAGE=\\"filename\\"` pointed to a file (complete path was supplied) that imports a LaTeX style file (that I named `matrixnew.sty` and) that defines a new command called `\matrixnew` which is the same as the original `\matrix` command but with a different name. The same TeX macro that was used for defining `\matrix` was used to define `\matrixnew`.  Doing so allows us to redefine `\matrix` without referring to the old `\matrix` definition (this old definition was for the `matrix` environment).
- the `-DNEWCOMMAND=\\"filename\\"`pointed to a file that redefined the `\matrix` command as `\newcommand{\matrix}[1]{\newcommand{\\}{\cr}\matrixnew[#1]`(note that I aslo had to redefine the newline command from `\\` to `\\cr` within the new definition of the `\matrix`).  Unfortunately, this new definition renders the `matrix` environment non-functional.  However, the other matrix-like environments are all functional, e.g., `pmatrix`, `bmatrix`, and `Bmatrix`.

To re-iterate, this new (re-complied) version of `mathtex` can only process the `\matrix{ ... }` command and not the `\begin{matrix} ... \end{matrix}` environment.  The reverse is true for my previous `mathtex` version.  `mimetex` can process both requests.

**Comment by justineuro** [comment]
There may be other concerns with using `mathtex`.  For the third example question (ID 38; on the graph of a piecewise function) that I gave above, the submitted request to `mathtex` sends a `\lt` `\gt` to mean `<` and `>`, respectively.  Unfortunately, both codes are not defined in LaTeX---the inequality signs are simply used.  I had to re-define the code sequences using `\newcommand{\lt}{<}`
and `\newcommand{\\gt}{>}` and again recompiled `mathtex`.

The non-strict  inequalities are not a problem as the codes `\le` and `\ge` are processed by `mathtex`.  Some of the sample problems that I've seen use the HTML escape codes `&lt;` and `&gt;` and avoid these problems.

**Comment by drlippman** [comment]
I wonder why mimetex supports `\lt` but mathtex doesn't.  Weird.  It would probably be possible to revise the asciimath-to-tex converters to output `<` instead.

Likewise you could probably modify them to output `\begin{matrix}` for matrices.  

I hope you'll understand that neither change is something I'm interested in spending time on, since for me the image fallback is only intended for that - a fallback - and mimetex works fine for that purpose.  For online display, MathJax or Katex are better approaches than using images.

**Comment by drlippman** [comment]
BTW, I just played around with this a bit.  Dealing with the `<` wasn't too hard; I'll go ahead and make that change.

I remember now why I never switched to `\begin{matrix}`.  mimetex seems to have a glitch where the expression `\left[\begin{matrix}{1}&{2}&{3}\\{4}&{5}&{6}\end{matrix}\right]` renders without the first element, and there's no simple work-around I've been able to find.

**Comment by justineuro** [comment]
The change to `<`, `>` would be great!  Thanks!

You are right about that glitch in `mimetex`.  I did notice that too but forgot about it.  Removing the enclosing curly braces for the entries of the matrix makes `mimetex` work fine, i.e., `\left[\begin{matrix}1&2&3\\4&5&6\end{matrix}` is rendered by both `mimetex` and `mathtex`. However, `\matrix{ ... }` is more convenient and there might be a good reason why we need those enclosing curly braces for the entries.  So leaving it as `\matrix`, as you suggested, is probably better. 

Thanks for looking into these!
