### ISSUE TITLE
mathjax 2.6?

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#12]
Not an issue but a request. Can mathas get mathjax updated to 2.6?

**Comment by drlippman** [comment]
Probably. Is there something in particular that was fixed that is prompting this request?
On Jan 17, 2016 1:26 AM, ericvanboven <notifications@github.com> wrote:Not an issue but a request Can mathas get mathjax updated to 26?

**Comment by ericvanboven** [comment]
Have some faculty who say some graphics do not display correctly with
mathjax but do with image based. I know I troubleshooted another problem
with a faculty member where a question was not working with mathjax 2.5 but
worked with the mathjax 2.6 beta and image based. In the end she had an
extra parenthesis in her  question code but mathjax 2.6 seemed to allow it
where 2.5 wouldnt.

On Sun, Jan 17, 2016 at 12:38 AM, David Lippman <notifications@github.com>
wrote:

> Probably. Is there something in particular that was fixed that is
> prompting this request?
> On Jan 17, 2016 1:26 AM, ericvanboven <notifications@github.com>
> wrote:Not an issue but a request Can mathas get mathjax updated to 26?
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drlippman/IMathAS/issues/12#issuecomment-172298561>.
>



-- 


*Eric Van Boven:* System Admin II

18401 N. 32nd Street, Phoenix, AZ  85032
phone | 607-78(77794)
email | eric.van.boven@paradisevalley.edu
website | www.paradisevalley.edu

**Comment by albong** [comment]
It looks like mathjax already got updated, but just to note: there was a problem with 2.5 and the latest version of chrome.
https://github.com/mathjax/MathJax/issues/1300

**Comment by ericvanboven** [comment]
Yup David updated it after I informed him its usefulness.
