### ISSUE TITLE
Several malformed hyperlinks

### ISSUE THREAD

**Issue by saiena** [drlippman/IMathAS#129]
"<a hre=" occurs instead of "<a href=" in several files:

course/course.php:
`
  100: 		$body = _("Course does not exist.  <a hre=\"../index.php\">Return to main 
`
i18n/de.po:
`
  656: msgid "Course does not exist.  <a hre=\"../index.php\">Return to main page</a>"
  658: "Kurs existiert nicht.  <a hre=\"../index.php\">Zurück zur Hauptseite</a>"
`
i18n/messages.po:
`
  520: msgid "Course does not exist.  <a hre=\"../index.php\">Return to main page</a>"
`

**Comment by drlippman** [comment]
Thanks.  I'll fix the one in course.php.  The other two are autogenerated by gettext from that file.
