### ISSUE TITLE
minor syntax issue in ccexport-generate.php

### ISSUE THREAD

**Issue by MathTV** [drlippman/IMathAS#131]
Line 412 is missing dollar sign:

    $canvout .= '<workflow_state>'.(row[6]==0?'unpublished':'active').'</workflow_state>'."\n";

should be:

    $canvout .= '<workflow_state>'.($row[6]==0?'unpublished':'active').'</workflow_state>'."\n";

**Comment by drlippman** [comment]
Thanks!
