### ISSUE TITLE
Exporting to Another LMS

### ISSUE THREAD

**Issue by ceh320** [drlippman/IMathAS#133]
Hope someone can help with this. When trying to do an export for another LMS I was getting an error 500 after clicking the Download Export Cartridge. I changed permissions on course/files/CCEXPORT4/ to 744 and now I'm getting an error 404 (not found). I've tried enabling debug mode, but don't know where to find the debug files. 
Any help with this will be greatly appreciated.

**Comment by ceh320** [comment]
Fixed this by installing php pecl-zip, which allows CCExport to compress.

**Comment by drlippman** [comment]
Ahh, yeah, the cc export requires that the Zip functions be available.  Most distros build php with it enabled by default.
