### ISSUE TITLE
IMathAS LTI not communicating with Canvas gradebook

### ISSUE THREAD

**Issue by akuyper** [drlippman/IMathAS#137]
Until about a week ago everything was working properly, but now grades from our IMathAS assignments are not being pushed to the Canvas grade book (or maybe Canvas is not accepting them).

I can still make exceptions to the due dates and that is all working properly. 

Any insight or suggestion on how to fix this would be greatly appreciated.

**Comment by drlippman** [comment]
Try adding `$CFG['LTI']['logupdate'] = true;` to your config.php, and it should start logging LTI updates into `/admin/import/ltiupdate.log`.  That will let you see if the updates are even being initiated.

If they are, then it's pretty hard to guess what might be causing the problem.  It's possible your server isn't allowing the curl calls to happen, or that Canvas is rejecting your requests for some reason.  In the current system, IMathAS doesn't wait for a reply from Canvas, so there's no easy way to log what's going on.

**Comment by akuyper** [comment]
We've added `$CFG['LTI']['logupdate'] = true;` to our config.php file and tried submitting a few assignments, but no log is being created. Could this be an indication that the LTI updates are not being initiated?

**Comment by drlippman** [comment]
Yes, it suggests that either the LTI updates are not being initiated, or the `/admin/import` directory wasn't correctly set up to be writable by the webserver by the install process.

Are these assignments being accessed directly by Canvas links?  The next thing you could check is looking at the database and seeing if the `imas_assessment_sessions` records for that assessment have values in the `lti_sourcedid` column.  If not, then the necessary data for grade return isn't getting received from Canvas.

**Comment by akuyper** [comment]
Yes, the assessments are being accessed directly by Canvas links (setup to open in new tab).

**Comment by akuyper** [comment]
Thank you for the help. Turns out that doing system reset did the trick. Probably should have started with that.
