### ISSUE TITLE
Gradebook errors in instructor and student view

### ISSUE THREAD

**Issue by mayronalfaro** [drlippman/IMathAS#139]
Help! With my recent installation of IMATHAS. I configured something wrong?
![errors](https://user-images.githubusercontent.com/46360069/50666245-77fc6580-0f79-11e9-9f9a-491eae05a01b.png)

**Comment by saiena** [comment]
Looks like you need to edit this line in your config.php file:

	//error reporting level.  Set to 0 for production servers.
	error_reporting(E_ALL & ~E_NOTICE);

**Comment by drlippman** [comment]
It looks like I need to add some sanity checks into the code, but like saiena suggested, turning off error reporting of Warnings is always a good idea.

**Comment by mayronalfaro** [comment]
Working I'll keep watching the updates. Great job.
