### ISSUE TITLE
Cannot select question libraries if IMathAS is in iframe

### ISSUE THREAD

**Issue by zjevik** [drlippman/IMathAS#144]
If IMathAS is loaded inside iframe (i.e. in Canvas) then a teacher cannot select different question libraries. The code in `/javascript/libtree2.js` uses "top". This will yield a DOMException for cross origin policy. The script should use "parent" instead in the lines 146-148.

**Comment by drlippman** [comment]
Thanks.  BTW you're always welcome to make a pull request for minor fixes like this to get the change in quicker :)

**Comment by zjevik** [comment]
Sounds good!
