### ISSUE TITLE
Simplified assignment solution incorrectly rejected

### ISSUE THREAD

**Issue by MURPHYENGINEERING** [drlippman/IMathAS#145]
> Find the derivative of f(x) = 3sqrt(x) - 2/x^8

This solution is accepted:

> 3/(2sqrt(x)) + 16/x^9

But this is marked as incorrect:

> (3x^9 + 32sqrt(x)) / (2sqrt(x^19))

![Screenshot 2019-06-11 at 7 13 03 AM](https://user-images.githubusercontent.com/39564257/59279218-6437e800-8c18-11e9-943f-37086ca94983.png)

**Comment by drlippman** [comment]
IMathAS itself will happily accept either answer.  If the latter answer was marked incorrect, it's because the question writer included additional format requirements.
