### ISSUE TITLE
Earlier versions

### ISSUE THREAD

**Issue by andib66** [drlippman/IMathAS#15]
Hello,

In the past you had earlier versions IMath, but I can't seem to find them now, or maybe I am not seeing them. Any help would be greatly appreciated.

Thank you!

**Comment by drlippman** [comment]
I stopped doing numbered versions about 7 years ago, when I switched to using version control.  Using git, you can backtrack the code to any previous commit (point in time).

    On Monday, February 8, 2016 11:35 AM, andib66 <notifications@github.com> wrote:
 

 Hello,In the past you had earlier versions IMath, but I can't seem to find them now, or maybe I am not seeing them Any help would be greatly appreciatedThank you!—

**Comment by andib66** [comment]
Thank you so much for your speedy reply.

Andi Berry
Instructional Lab Assistant
Valencia College Osceola Campus
321.682.4835  MC: 6-1
[cid:image002.png@01CFED40.E0AA22D0]
