### ISSUE TITLE
Mass Send does not perform FirstName, LastName substitution for copies sent to teachers and tutors

### ISSUE THREAD

**Issue by saiena** [drlippman/IMathAS#153]
This code in masssend.php sends the raw $message to teachers
`
send_email($addy, $sendfrom, $subjectPost, $message, array($self), array(), 5);  
`

But the related code that sends to students and tutors performs substitution:
`
send_email($addy, $sendfrom, $subjectPost, str_replace(array('LastName','FirstName'),array($lastnames[$k],$firstnames[$k]),$message), array($self), array(), 5);  
`

**Comment by saiena** [comment]
messages sent to tutors also fails to perform substitution.

**Comment by drlippman** [comment]
Does it really make sense to make the substitution for teachers/tutors?  Usually if you're sending a copy to them, it's so they have a copy of the message and who it was sent to.  The message isn't really addressed to the teacher or tutor.

**Comment by saiena** [comment]
XYZ Staff agrees with your conclusion. Sorry for the bother.
