### ISSUE TITLE
Imathas does much help in this coronavirus outbreak

### ISSUE THREAD

**Issue by cchuang2009** [drlippman/IMathAS#165]
Under the threaten of campus closing, we try to set up a remote learning environment. Thanks to imathas, we setup the system on a live linux system and on Mac pro immediately. And upload lectures, and create the assessment system for calculus class. Thanks the develop group of imathas . If someone want to get more details, we could feedback what we have done.
Chi-ching huang

**Comment by drlippman** [comment]
I'm glad it can help.  I'm assuming you know about the public installation, MyOpenMath, which can be a good source of content if you're running your own install.
