### ISSUE TITLE
Admin/Instructor Privileges

### ISSUE THREAD

**Issue by justineuro** [drlippman/IMathAS#193]
A new install done by following the installation steps given in the [`README.md`](https://github.com/drlippman/IMathAS/blob/master/readme.md) doesn't give the **Admin Page** section on login: 

![Screenshot_2020-10-02_16-41-36](https://user-images.githubusercontent.com/7970053/94904649-355d1980-04ce-11eb-84aa-e411975d1371.png)

That is, logging-in as **root** after the default install doesn't give teacher privileges to **root**.

**Comment by drlippman** [comment]
Odd.  The database insert in setupdb.php has the rights hardcoded as Admin, so I'm not sure why it's not working for you.  Can you manually check the database and see what the recorded "rights" value is for that user?

**Comment by justineuro** [comment]
For **root**, the **rights** is encoded as **100**; **specialrights** as **112**.

**Comment by drlippman** [comment]
Very odd. That's the right value. Not sure what's going on.

**Comment by justineuro** [comment]
In addition, the user's ID doesn't appear in the welcome message ...

**Comment by drlippman** [comment]
Yes, you definitely have some weird issue going on, but I have no idea what it is.  I haven't seen this issue myself when doing a fresh install. Check your error logs and see if they can shed any light on it.

**Comment by justineuro** [comment]
The same result was obtained when I cloned the repository into a local directory.  Many thanks, by the way, for looking into this.

**Comment by justineuro** [comment]
Just `git pull`-ed a few hours ago and everything seems to be fine now.

![Screenshot_2020-10-03_23-53-15](https://user-images.githubusercontent.com/7970053/94995924-04ffa300-05d4-11eb-8ccc-5923843518c2.png)

The `setupdb.php` install log ia attached: [IMathAS-init-2020Oct03-master-2.pdf](https://github.com/drlippman/IMathAS/files/5321931/IMathAS-init-2020Oct03-master-2.pdf).

Many thanks!

**Comment by justineuro** [comment]
May we now close this?

**Comment by drlippman** [comment]
Looks like the problem was that the data migrations failed partway through when you did the first install.  Glad you were able to resolve it :)
