### ISSUE TITLE
Can we get mathjax updated to 2.6.1

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#22]
When you have a chance can we get mathjax updated to 2.6.1 with some bug fixes for 2.6.
https://github.com/mathjax/MathJax/issues?utf8=%E2%9C%93&q=milestone%3A%22MathJax+v2.6.1%22

**Comment by drlippman** [comment]
Just updated in 4ce4489a294751f9b0d071392acc99ff77cd786c
