### ISSUE TITLE
[Documentation] Plot function endpoint markers can be arrows

### ISSUE THREAD

**Issue by onomou** [drlippman/IMathAS#220]
According to [this thread](https://www.myopenmath.com/forums/posts.php?cid=1&forum=38&thread=465773&page=-4), `startmarker` and `endmarker` can also be `"arrow"`.

https://github.com/drlippman/IMathAS/blob/370551e863436b8d5c4b696602b15998f15e2517/help.html#L2264

So this could read ` <li><strong>startmarker,endmarker</strong>: can be "open" or "closed" (dots), "arrow," or anything else for none</li> ` if you like.

**Comment by drlippman** [comment]
Thanks
