### ISSUE TITLE
Spelling Error: gb extension should be gd extension

### ISSUE THREAD

**Issue by dirtybirdnj** [drlippman/IMathAS#252]
Hi I'm doing some work for a client evaluating this repo, and I came across this line when getting the project running locally.

>It appears your PHP does not have the gb extension installed

I think this error message should reference the "gd" library, not "gb" which does not exist. Took me a good 20 minutes to track the problem down. Pretty sure this is a spelling error because the conditional that displays this message is referring to the `gd_info()` function.

https://github.com/drlippman/IMathAS/blob/0cb9663b7b41809969b074f22b516773dc369459/install.php#L202

**Comment by dirtybirdnj** [comment]
https://github.com/drlippman/IMathAS/pull/253

**Comment by drlippman** [comment]
Thanks for the fix.
