### ISSUE TITLE
Lost MathJax functionality 

### ISSUE THREAD

**Issue by enoxos** [drlippman/IMathAS#254]
Hello,
Somehow, I lost the MathJax functionality and the server uses the fall back link for mimetex.cgi.
I performed a git pull for any updates, but no luck.
Any direction to look into?
Not sure what actually happen, but I was playing around with the Pandoc feature.
Thank you

**Comment by drlippman** [comment]
Try logging out and back in. Sound like your session user preferences got overridden.  If that doesn't work, check your user preferences.

**Comment by enoxos** [comment]
Restarting the sever did not work, but logging out and back on did the trick. 
Is it possible to install mathJS locally or does imathas only use CDN links?
Thank you

**Comment by drlippman** [comment]
Yes you can install it in a mathjax subdirectory and in your config.php use the $CFG['GEN']['uselocaljs'] option.

**Comment by enoxos** [comment]
Will try it and report back.
Thank you for you help.
