### ISSUE TITLE
imathas Chat: this is not an issue, maybe a request

### ISSUE THREAD

**Issue by enoxos** [drlippman/IMathAS#259]
Hello,
I was wondering if there any plans in implementing a chat into imathas. It maybe useful for teachers to have some open hours where students can drop in and ask a quick questions. Perhaps the chat can use Latex code. Rocket chat (open source) does use katex flavor.
Just putting this out there to see if the developers have any plans.
Thank you for an excellent software.

**Comment by drlippman** [comment]
No, I have no plans to implement chat.  I used to have a crappy version of chat, but ditched it because it didn't work well.  Good chat requires things like websockets, and websockets require a lot of server resources.  Not to mention chat is a totally different beast well outside the scope of a homework system, and I've got my hand full with the existing scope of the system.

There are other options out there for chat.  I suggest using one of them.

**Comment by enoxos** [comment]
Thanks for your reply. I am currently looking into Rocket Chat. Do you have perhaps a better recommendation? Also, will you be willing to share that old chat code of yours? 
Thanks

**Comment by drlippman** [comment]
I don't have a good recommendation.  Most people use video chat now rather than text-based chat.

If you look back in the git history, and checkout something prior to 9/13/2016, you should be able to find the old "mathchat" code.

**Comment by enoxos** [comment]
Thank you, I found the code.

**Comment by enoxos** [comment]
Thank you for the reply. I was able to take a look at the code from back then and I am intrigued now to see the chat in action. However, I am having some issues with the correct WAMP stack versions making it work. I get errors related to `mysql` and `mysqli` compatibility which are due to deprecation(s) in MySQL version 5.5, but several versions between 5.0 and 5.5 have not worked.  I am also having some difficult time getting MySQL with version less than 5.0. 
Do you happen to know which versions of MySQL and PHP will work with that version of ismathas?
Thank you so much.

**Comment by drlippman** [comment]
Maybe PHP5.6.  Didnt think mysql version mattered. 
And that code won't be compatible with the current config.php, if it uses that.  I removed the mathchat when we migrated from the deprecated mysql database connector to PDO.  You're on your own to figure out how to make it work.

**Comment by enoxos** [comment]
I thought that a native chat maybe a good idea, at least for small installations like a single school environment with the benefit that the credentials are the same. Several schools would probably require a third-party chat with a web-socket like Rocket-Chat which uses its own data files and separate credentials. 
Hopefully I can revive the native chat and post the code for anyone else that wants to use it.
Thanks a bunch.
