### ISSUE TITLE
bug in showtest.php change from commit 716a3ec6820744af019c091d1ec5afb98de8227b 

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#26]
When using the showtest.php from this commit it appears that  homework/quizes that are setup to use Display method: embedded  users can no longer can click the submit button.

**Comment by drlippman** [comment]
I thought I fixed this already. Maybe I forgot to commit the change. I'll check next time I'm at a computer.
On Mar 31, 2016 8:02 AM, ericvanboven <notifications@github.com> wrote:When using the showtest.php from this commit it appears that  homework/quizes that are setup to use Display method: embedded  users can no longer can click the submit button.
