### ISSUE TITLE
database insert fails for new user and new course

### ISSUE THREAD

**Issue by cooplogic** [drlippman/IMathAS#27]
For new users (actions.php?action=newuser&confirmed=true) , the hideonpostswidget field is not set, but it's expected to be not null. (Query failed : Field 'hideonpostswidget' doesn't have a default value)

For adding a course, the outcomes and ancestor fields are not set, but they are expected to be not null. I can modify the database to make them null, or I could add a field in the insert call in the php, but I am not sure if there is a specific value that is expected for these.

Any insight would be appreciated. 

Thanks,

**Comment by drlippman** [comment]
This is caused by MYSQL's "strict" mode in 5.6+.  The best/easiest fix is to turn if off.  See [this page](https://www.euperia.com/development/mysql-fix-field-doesnt-default-value/1509) for example.

**Comment by cooplogic** [comment]
I patched the php so it turns off the strict mode on a per session basis. What is the protocol for committing changes on this project?

**Comment by drlippman** [comment]
You're welcome to make a pull request. 
On May 23, 2016 4:33 PM, cooplogic <notifications@github.com> wrote:I patched the php so it turns off the strict mode on a per session basis. What is the protocol for committing changes on this project?

**Comment by cooplogic** [comment]
done.
