### ISSUE TITLE
Mobile version doesn't show course reports link.

### ISSUE THREAD

**Issue by cooplogic** [drlippman/IMathAS#37]
The menu for the mobile site doesn't show the course reports link after the gradebook link (where I would expect it to go), but the page loads fine if you type in the url.

**Comment by drlippman** [comment]
Mobile doesn't show any of the left side navigation. Eventually I'll figure out a way to include it, but it's not a priority. The reports would look pretty ugly on mobile anyway.
On Jun 24, 2016 7:42 PM, David Cooper <notifications@github.com> wrote:The menu for the mobile site doesn't show the course reports link after the gradebook link (where I would expect it to go), but the page loads fine if you type in the url.
