### ISSUE TITLE
JWKS empty on install

### ISSUE THREAD

**Issue by AlexGellert** [drlippman/IMathAS#412]
Is there anyway to populate the jwks.php when its empty after install? Everything else looks to be working fine but my /IMathAS/lti/jwks.php is just an empty array called keys

```
keys: []
```

**Comment by drlippman** [comment]
Go to the Admin page, click on LTI 1.3 Platforms, then Manage Private Keys, and add a private key.

**Comment by AlexGellert** [comment]
Nice thanks for the quick response that resolved that issue. Running into two different ones depending on if I install at account level or course level but will try and muddle through.
