### ISSUE TITLE
Mathjax 2.7

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#65]
Any chance of going to mathjax 2.7. https://www.mathjax.org/mathjax-v2-7-now-available/
Over 60 bugs fixed.

**Comment by drlippman** [comment]
I thought I switched the main repo to use the MathJax CDN, which always points to the latest version. I'll double check.  But yes, I should update the stashed local version too.On Jan 9, 2017 12:49 PM, ericvanboven <notifications@github.com> wrote:Any chance of going to mathjax 2.7. https://www.mathjax.org/mathjax-v2-7-now-available/
Over 60 bugs fixed.

**Comment by drlippman** [comment]
Updated in d9d8716ad81604b498494167e7959140d789582b
