### ISSUE TITLE
forminlinebutton in embedded assessment

### ISSUE THREAD

**Issue by gksander** [drlippman/IMathAS#66]
In Embedded assessments, inline buttons (via forminlinebutton) are mis-behaving. On first page load, all inline buttons work as intended. But on question submit, periodically the inline buttons will get renamed/renumbered.

For example, span id='inlinebtn1' will get changed to span id='inlinebtn2' on question submit, which then links the span to the wrong display div. 

I'll try to look into this if I have the time, but you could probably spot the issue much quicker than me.

---------------------------------

It looks like in macros.php, line 2236, $GLOBALS['inlinebuttoncnt'] is being used. In embedded assessments, it look like that global variable is being reset due to the async nature of the embed. Every submit, the inline buttons are getting id'ed as inlinebtn2.

**Comment by drlippman** [comment]
Fixed in dff41c501892922ab4fcbcf6e22a9818066087fc
