### ISSUE TITLE
Problems with session cookies?

### ISSUE THREAD

**Issue by mfrellum** [drlippman/IMathAS#7]
I can not login after setup of IMathAS. I get error:
"Unable to establish a session.  Check that your browser is set to allow session cookies". The browsers are all set to accept cookies and work with MyOpenMath.
IMathas cloned 11. feb and installed on latest Ubuntu 14.04 with latest Apache2 and MariaDB 10.1 (in Docker containers). I have tried to set up a different session storage than the default, but no change.

**Comment by drlippman** [comment]
I don't know what to suggest - I'm not having issues on either of my development servers or my production servers.

You might compare your loginpage.php against loginpage.php.dist to make sure you don't have anything out of the ordinary in the session check section, and make sure you have the code in loginpage that establishes $_SESSION['challenge'].

If the challenge is being defined correctly but lost on submit, that suggests an issue with session storage.

**Comment by mfrellum** [comment]
There seems to be a problem with session storage for me. Is /tmp/persistent/imathas/session the default session storage?
I got it half working by making a folder in IMathAS root called sessions, and setting "sessions" as session path in config.php. Than it worked for student but not for admin, and only for a short while. I will try to start from scratch, and see if I can get sessions right.

**Comment by drlippman** [comment]
On all my installations, I don't have $sessionpath set in config.php, I just use whatever PHP's default is and have never had problems.

The only reason you should need to need to set the sessionpath is if you're running the software on a clustered server farm, where each request might go to a different server. In that case, you need $sessionpath to be set to a shared file space that all the servers have access to.  But that's getting in to PHP configuration stuff, which is beyond my expertise.

**Comment by mfrellum** [comment]
I have not used PHP for 5-6 years, so I'm on a steep relearning curve ;)
The virtual test environment of Docker-containers I used was http only and no real domain (only ip).
On a real server with https and a domain it works :-)

**Comment by gksander** [comment]
I also experienced troubles logging in after installing iMathAS locally. For me, switching my Apache port from 8888 to 80 immediately solved the issue.

(I'm a little late to this party.)
