### ISSUE TITLE
ASCIIMath in /course/addquestions.php

### ISSUE THREAD

**Issue by gksander** [drlippman/IMathAS#76]
I'm using the embedded assessment type to make interactive lessons. I'd like to convert to the new method of interlacing text with questions from the /course/addquestions.php page, but I'm running into the following issue:

* I like to write everything using HTML markup, for adding classes, not letting tinyMCE mis-guess what I want, **and** so that back-ticks don't render math-tags in the editor.
* In addquestions.php, if you add back-ticks to the inter-laced text via HTML, the next time you load the questions page, MathJax/ASCIImath will sweep through and convert all of the delimited math to MathML tags -- which, as you know, is extremely painful to deal with via HTML.
* Because of this, I'm doing all of my inter-laced text from the assessment settings paged, because that page isn't rendering my back-ticks.

Do you suppose there's an easy way to deal with this? addquestions.php renders math on the page, for math typesetting in the question descriptions -- so I assume it just does a full sweep of the page. I'm not sure if there's any way to *exclude* the interlaced text from that or not.

A second, and much less pressing, question. TinyMCE's default code editor isn't really much of an editor. There appears to be a third party CodeMirror [plugin](https://github.com/christiaan/tinymce-codemirror) for TinyMCE. Do you think it would be worth incorporating this in? I'm not sure if there are enough users editing HTML to warrant loading the plugin each time TinyMCE is used. Thoughts?

**Comment by drlippman** [comment]
The rendering on reload is probably a TinyMCE thing, but I'll have to look into it.  I've noticed rerenderering of math on the addquestions page reload is really slow, so I've been meaning to explore what's going on there anyway.

**Comment by drlippman** [comment]
BTW, on your CodeMirror question:  Most people don't use tiny for editing HTML directly, except maybe for fixing something that doesn't isn't quite right.  I don't think adding CodeMirror to tiny makes a ton of sense.  But if you really want to do a lot of editing, you could look at adding a "use CodeMirror instead of tinymce" user preference option.  Not something I'm interested in working on, though.
