### ISSUE TITLE
Rational Function Graphs Displaying Incorrectly

### ISSUE THREAD

**Issue by CDHolloway** [drlippman/IMathAS#85]
I had issues with some algorithmically generated graphs displaying incorrectly. Near what should be an asymptote, the graph would instead have a vertical line segment. (This seems to only happen when the vertical asymptote is only one unit away from a root, and possibly only when both occur on the negative x-axis.)

To check whether it might simply be a problem with my algorithm, I wrote the following:

$test=showplot("($a(x+2))/(x+3)",-10,10,-10,10,1,1,400,400)

This is the graph that resulted:

![image](https://user-images.githubusercontent.com/29465832/27197390-a6fc4130-51d3-11e7-9c68-a17e71ebf3fe.png)

**Comment by drlippman** [comment]
Yeah, this is a pretty common issue with any graphing utility - rational functions are graphed by calculating points and connecting the dots, and if the function changes too rapidly, it can't detect the jump across an asymptote (currently, the code looks to see if the graph jumps from a point >ymax to a point <ymin).  I'll see if I can add in some additional sanity checks, but sometimes this is just going to happen.  You can often workaround it by plotting the left and right halves of the function separately.

**Comment by CDHolloway** [comment]
I rewrote it as two separate functions like you suggested, and that seems to have taken care of the problem. I can live with that.

**Comment by drlippman** [comment]
I've made some improvements, and hopefully this is mostly resolved now.
