### ISSUE TITLE
course uploaded file missing the / in the view link

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#87]
When attaching/uploading a file in a course the link displays correctly in the box but the url is missing the / and has %2F instead and the url does not work. If I go back to the course page the url is correct.

![imathas bug](https://user-images.githubusercontent.com/10040354/27554357-069f3e84-5a63-11e7-82b5-d5ef352faa6c.png)

**Comment by drlippman** [comment]
Yup, looks like the links work OK on the main course page, but the View link is over-encoded.
