### ISSUE TITLE
As a student, I can view (some) gradebook details for other classes

### ISSUE THREAD

**Issue by seizethedave** [drlippman/IMathAS#9]
This is something I noticed using wamap.org. Hope this is an appropriate place to report this.

A few examples:

https://www.wamap.org/course/gradebook.php?cid=9956
https://www.wamap.org/course/gradebook.php?cid=9957
https://www.wamap.org/course/gradebook.php?cid=9958

Looks like it's a teacher-centric view, although I don't think I can actually modify or see anything sensitive. I see the various names of course sections, and the course name, etc.

![screen shot 2015-05-27 at 7 19 46 pm](https://cloud.githubusercontent.com/assets/133913/7851486/83ebb84c-04a5-11e5-8ab2-0eec09873b15.png)

**Comment by drlippman** [comment]
Whoops, yeah that shouldn't be showing.  Thanks for reporting it - I'll get it fixed. 


     On Wednesday, May 27, 2015 7:23 PM, David Grant <notifications@github.com> wrote:
   

 This is something I noticed using wamap.org. Hope this is an appropriate place to report this.A few examples:https://www.wamap.org/course/gradebook.php?cid=9956
https://www.wamap.org/course/gradebook.php?cid=9957
https://www.wamap.org/course/gradebook.php?cid=9958Looks like it's a teacher-centric view, although I don't think I can actually modify or see anything sensitive. I see the various names of course sections, and the course name, etc.—
