### ISSUE TITLE
Email address bug

### ISSUE THREAD

**Issue by ericvanboven** [drlippman/IMathAS#97]
When sending emails it appears to be trying to inject persons first and last name onto the front of the email. Was working fine a month ago and just updated Wednesday. Some email seems to go through correctly when I send a message and have it send an email about that message it went to my account correctly. It might be the mass email portion.

**Comment by drlippman** [comment]
Is there a particular page or method of sending an email that's triggering this error?  It sounds like you think it might be the mass email code?

**Comment by drlippman** [comment]
Nevermind, I see the problem in the masssend.  The email is being sanitized after being constructed into an email string like `John Smith <jsmith@site.com>`.  I'll work on a fix.
